### ISSUE TITLE
array_find return value seems to be broken in 6.8.0

### ISSUE THREAD

**Issue by Daeroni** [vimeo/psalm#11331]
When upgrading to 6.8.0 I noticed that array_fid return value seems to be broken, defaulting to mixed instead of deducing it from the input array

https://psalm.dev/r/1ad7073d07

```
Psalm output (using commit [9ae98ac](https://github.com/vimeo/psalm/commit/9ae98ac) on PHP 8.2.27): 

INFO: [Trace](https://psalm.dev/224) - 22:5 - $accounts: list<Account>

INFO: [MixedAssignment](https://psalm.dev/032) - 25:2 - Unable to determine the type that $account is being assigned to

INFO: [Trace](https://psalm.dev/224) - 25:2 - $account: mixed

INFO: [MixedReturnStatement](https://psalm.dev/138) - 34:12 - Could not infer a return type

```

```
Expected output (on psalm 6.7.1):

INFO: [Trace](https://psalm.dev/224) - 22:5 - $accounts: list<Account>

INFO: [Trace](https://psalm.dev/224) - 25:2 - $account: Account|null

```

**Comment by orklah** [comment]
Seems fixed in 6.8.7

**Comment by danog** [comment]
Not fixed

**Comment by djmetzle** [comment]
A repro of the issue: https://psalm.dev/r/0caf23f641

**Comment by niconoe-** [comment]
Issue is still not fixed: https://psalm.dev/r/eb90c33a4c

I'm not expecting "mixed" but "int" (or, at least, "null|int").
