### ISSUE TITLE
Cannot infer type of templated `Foo&Proxy<Foo>` methods with `class-string<Foo>`

### ISSUE THREAD

**Issue by Ocramius** [vimeo/psalm#1675]
Similar to #1673 and #1674, type inference cannot determine the output of a call to `foo()` in following scenario:

```php
<?php

/** @psalm-template SomeType */
interface ParentType
{
    /** @psalm-return SomeType */
    function foo();
}

/** @psalm-template SomeOtherType */
interface ChildType extends ParentType
{
}

class ConcreteParameter
{
    function sayHello() : string
    {
        return 'hi';
    }
}

/**
 * @psalm-template RealObjectType as object
 *
 * @psalm-param class-string<RealObjectType> $className
 *
 * @psalm-return RealObjectType&ChildType<RealObjectType>&ParentType<RealObjectType>
 */
function makeConcrete(string $class) : object
{
    return new class() extends ConcreteParameter implements ChildType {
        public function foo() {
            return $this;
        }
    };
}

echo makeConcrete(ConcreteParameter::class)->foo()->sayHello();
```

This may be because of `ChildType` taking precedence over `ParentType` (just an assumption of mine).

https://psalm.dev/r/8178556639

Verified also locally on latest `master`:

```
Scanning files...
Analyzing files...

ERROR: MixedArgument - issue.php:39:6 - Argument 1 of echo cannot be mixed, expecting string
echo makeConcrete(ConcreteParameter::class)->foo()->sayHello();


ERROR: MixedMethodCall - issue.php:39:46 - Cannot determine the type of the object on the left hand side of this expression
echo makeConcrete(ConcreteParameter::class)->foo()->sayHello();


ERROR: MixedMethodCall - issue.php:39:53 - Cannot determine the type of the object on the left hand side of this expression
echo makeConcrete(ConcreteParameter::class)->foo()->sayHello();


------------------------------
3 errors found
------------------------------

Checks took 0.23 seconds and used 99.636MB of memory
Psalm was unable to infer types in the codebase
```

**Comment by Ocramius** [comment]
Note: no issues if I remove `@psalm-template` from `makeConcrete()` and hardcode the generic type:

```php
<?php

/** @psalm-template SomeType */
interface ParentType
{
    /** @psalm-return SomeType */
    function foo();
}

/** @psalm-template SomeOtherType */
interface ChildType extends ParentType
{
}

class ConcreteParameter
{
    function sayHello() : string
    {
        return 'hi';
    }
}

/**
 * @psalm-return ConcreteParameter&ChildType<ConcreteParameter>&ParentType<ConcreteParameter>
 */
function makeConcrete() : object
{
    return new class() extends ConcreteParameter implements ChildType {
        public function foo() {
            return $this;
        }
    };
}

echo makeConcrete()->foo()->sayHello();
```

**Comment by muglug** [comment]
OK what is actually happening here? `$class`/`$className` isn't used, so I wonder how the class is being generated

**Comment by Ocramius** [comment]
The real code uses `eval()` here, with lots of things behind there. I stripped all that out for a simple reproducer.

**Comment by muglug** [comment]
Right, I thought it might - anyhow, this is now fixed (in 62dacaf): https://psalm.dev/r/4735271151

**Comment by weirdan** [comment]
@Ocramius but you need to fix your parameter name: docblock specifies type for `$className`, but function signature uses `$class`.

**Comment by weirdan** [comment]
@muglug Shouldn't Psalm complain about `ChildType` inheriting `ParentType`, but not providing a way to fill in the parent type parameter?

**Comment by Ocramius** [comment]
> @Ocramius but you need to fix your parameter name: docblock specifies type for `$className`, but function signature uses `$class`.

Indeed, did the usual mess while creating the example ^_^'

**Comment by Ocramius** [comment]
I've just tried 62dacaf locally and still get an issue that is very similar to this: trying to somehow isolate it.

**Comment by Ocramius** [comment]
Reported #1677 based on findings after this fix. Fix seems to work, but sorting issues in intersection types are likely still hidden/existing.
