### ISSUE TITLE
ParseError in (ignored) vendor symfony/polyfill-mbstring/bootstrap80.php

### ISSUE THREAD

**Issue by simonberger** [vimeo/psalm#4961]
In two symfony 4.4 projects we use PHP 7.2.
After updating to the [newest release 1.22.0](https://github.com/symfony/polyfill-mbstring/compare/v1.20.0...v1.22.0#diff-a97bb9776f637d300bee07c901a6ca59a2378845f507441b74939327606fc0f6) of symfony/polyfill-mbstring wo got the following new error after running psalm

```
ERROR: ParseError - vendor/symfony/polyfill-mbstring/bootstrap80.php:125:86 - Syntax error, unexpected '=' on line 125 (see https://psalm.dev/173)
    function mb_scrub(string $string, string $encoding = null): string { $encoding ??= mb_internal_encoding(); return mb_convert_encoding($string, $encoding, $encoding); }
```

The vendor folder itself is ignored.

While I understand this cannot be parsed by PHP 7.2, I do not understand why the PHP 8 bootstrap file is analysed at all. The only reference is in symfony packages with a PHP version check.

```
if (\PHP_VERSION_ID >= 80000) {
    return require __DIR__.'/bootstrap80.php';
}
```

Do I miss something or is this a problem in psalm?

**Comment by weirdan** [comment]
Psalm doesn't understand version-conditional code. Mind creating a minimal reproducer in a separate repo? I'd like to try to implement this.

**Comment by simonberger** [comment]
Here you go https://github.com/simonberger/psalmbug

Very minimal. There is no project file needed for it to fail
Why is this file read without any reference. Not even to the package.

**Comment by orklah** [comment]
functions are a special case in composer, they're loaded automatically in global scope. You must have a dependancy that needs the polyfill, which means composer have to load the functions for your dependancy

**Comment by simonberger** [comment]
We are still looking at a project with zero files to analyze which (in theory) means zero dependencies. Obviously something triggers psalm to read it I don't know its internals to make guesses.

**Comment by Tomanhez** [comment]
`<ignoreFiles><directory name="vendor" /></ignoreFiles>` doesn't work in this case. I tried add ignore directly `<ignoreFiles><file name="vendor/symfony/polyfill-mbstring/bootstrap80.php"</ignoreFiles>`, but it doesn't work too. Someone tried fix this issue in `symfony/polyfill-mbstring`, but looks like problem is `vimeo/psalm` site. https://github.com/symfony/polyfill/pull/327

**Comment by simonberger** [comment]
> `<ignoreFiles><directory name="vendor" /></ignoreFiles>` doesn't work in this case. I tried add ignore directly `<ignoreFiles><file name="vendor/symfony/polyfill-mbstring/bootstrap80.php"</ignoreFiles>`, but it doesn't work too. Someone tried fix this issue in `symfony/polyfill-mbstring`, but looks like problem is `vimeo/psalm` site. [symfony/polyfill#327](https://github.com/symfony/polyfill/pull/327)

I also think symfony-polyfill is totally fine.

**Comment by klebann** [comment]
I have same problem.
I want to add that it doesn't happend every time I run Psalm with ` --no-diff `.

**Comment by AlexP11223** [comment]
> Obviously something triggers psalm to read

I think it just parses everything in `vendor` before looking into your code? e.g. see `psalm --debug`

And yeah, we have the same issue in a PHP 7.2+ project  :)

**Comment by weirdan** [comment]
> I think it just parses everything in vendor before looking into your code?

@AlexP11223 It's a bit more complex. Psalm tracks what files were included during autoload registration (e.g. those in `autoload.files` entries of installed packages) and parses them, those referenced by them and so on.

@simonberger thanks for the reproducer.

**Comment by weirdan** [comment]
I'm going to propose a PR that would avoid scanning files that are conditionally included based on `PHP_VERSION_ID` (as is the case with multiple symfony polyfills).

**Comment by dshafik** [comment]
@weirdan that would work great, would it also be possible to add a config option to scope files to minimum PHP versions? 

There are definitely other different ways of doing this, such as:

```
$version = phpversion();
$version = PHP_MAJOR_VERSION . PHP_MINOR_VERSION;
```

**Comment by weirdan** [comment]
> would it also be possible to add a config option to scope files to minimum PHP versions?

Can you elaborate?

> There are definitely other different ways of doing this

With #4967 I'm not aiming to fix all possible cases, just those common enough that people reported them. Symfony polyfills are certainly common, and they use `PHP_VERSION_ID`. It can be extended later when other patterns surface being used in the wild.

**Comment by dshafik** [comment]
> Can you elaborate?

Something like this:

```xml
<projectFiles>
    <directory name="app"/>
    <ignoreFiles>
        <file name="./vendor/symfony/polyfill-mbstring/bootstrap80.php" min-version="8.0" />
    </ignoreFiles>
</projectFiles>
```

or maybe something like:

```xml
<projectFiles>
    <directory name="app"/>
    <ignoreFiles>
        <php min-version="8.0">
             <file name="./vendor/symfony/polyfill-mbstring/bootstrap80.php" />
        </php>
    </ignoreFiles>
</projectFiles>
```

**Comment by weirdan** [comment]
That wouldn't be necessary, as those files would be omitted when scanning based on actual conditions of the `if` statements they are wrapped into.

**Comment by nicolas-grekas** [comment]
Would psalm parse the file if it were named bootstrap.php8?
That's z change I'd be ok to do if yes.

**Comment by weirdan** [comment]
> Would psalm parse the file if it were named bootstrap.php8?

It would still parse the file.

**Comment by klebann** [comment]
How can I update psalm with this bugfix using composer?
Does I need to wait for new release?

**Comment by simonberger** [comment]
@klebann you can also require `dev-master` to get the fix.

**Comment by orklah** [comment]
you can use `composer require --dev vimeo/psalm:master` to use directly the last commit made here. Beware of stability though, it may break at any moment and does not necessarily reflect what will be in the next release. I'd advise going back to a named release as soon as the fix is released if you can.

**Comment by klebann** [comment]
Thanks!

**Comment by dshafik** [comment]
For anyone not wanting to use the master branch of psalm, you can explicitly specify a version of `symfony/polyfill-mbstring` **without** the offending file:

```
composer require symfony/polyfill-mbstring:v1.20.0
```

**Comment by XedinUnknown** [comment]
I still don't get why issues are reporting for an ignored folder, or even explicitly ignored file.

**Comment by trsh** [comment]
I am facing this issue. What is the solution, workaround?

**Comment by orklah** [comment]
You should be able to update psalm, there was a new release with the fix

**Comment by XedinUnknown** [comment]
This seems to still require adding the file to `<ignoreFiles>`. Is that correct?

**Comment by weirdan** [comment]
@XedinUnknown `vendor` folder is usually ignored already.

**Comment by XedinUnknown** [comment]
Yup, and yet the issue was that it was throwing an error due to bad syntax inside the already ignored `vendor`. In my latest project, I had to add `vendor` `<ignoreFiles>` to get this to work.
